# IRIS Dataset

In [1]:
import numpy as np
import pandas as pd
from sklearn import datasets
from scipy.optimize import minimize

<table><tr><td><img src='flower1.jpg' height="300" width="300"></td><td><img src='flower2.jpg' height="300" width="300"></td></tr></table>

In [2]:
iris = datasets.load_iris() #Dataset iris da sklearn

In [3]:
iris.feature_names #nomi delle features

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [4]:
iris.target_names #classi

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [5]:
X = iris.data #input
y = iris.target

In [6]:
print(X.shape, y.shape)

(150, 4) (150,)


In [7]:
iris_df = pd.DataFrame(np.c_[X, y], columns = ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)', 'class'])

In [8]:
pd.set_option('display.max_rows', iris_df.shape[0]+1)
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
5                  5.4               3.9                1.7               0.4   
6                  4.6               3.4                1.4               0.3   
7                  5.0               3.4                1.5               0.2   
8                  4.4               2.9                1.4               0.2   
9                  4.9               3.1                1.5               0.1   
10                 5.4               3.7                1.5               0.2   
11                 4.8               3.4                1.6               0.2   
12                 4.8               3.0                1.4               0.1   
13                 4.3               3.0                1.1               0.1   
14                 5.8               4.0                1.2               0.2   
15                 5.7               4.4                1.5               0.4   
16                 5.4               3.9                1.3               0.4   
17                 5.1               3.5                1.4               0.3   
18                 5.7               3.8                1.7               0.3   
19                 5.1               3.8                1.5               0.3   
20                 5.4               3.4                1.7               0.2   
21                 5.1               3.7                1.5               0.4   
22                 4.6               3.6                1.0               0.2   
23                 5.1               3.3                1.7               0.5   
24                 4.8               3.4                1.9               0.2   
25                 5.0               3.0                1.6               0.2   
26                 5.0               3.4                1.6               0.4   
27                 5.2               3.5                1.5               0.2   
28                 5.2               3.4                1.4               0.2   
29                 4.7               3.2                1.6               0.2   
30                 4.8               3.1                1.6               0.2   
31                 5.4               3.4                1.5               0.4   
32                 5.2               4.1                1.5               0.1   
33                 5.5               4.2                1.4               0.2   
34                 4.9               3.1                1.5               0.2   
35                 5.0               3.2                1.2               0.2   
36                 5.5               3.5                1.3               0.2   
37                 4.9               3.6                1.4               0.1   
38                 4.4               3.0                1.3               0.2   
39                 5.1               3.4                1.5               0.2   
40                 5.0               3.5                1.3               0.3   
41                 4.5               2.3                1.3               0.3   
42                 4.4               3.2                1.3               0.2   
43                 5.0               3.5                1.6               0.6   
44                 5.1               3.8                1.9               0.4   
45                 4.8               3.0                1.4               0.3   
46                 5.1               3.8                1.6               0.2   
47                 4.6               3.2                1.4               0.2   
48                 5.3              

In [9]:
print("Numero elementi classe 0 : {}".format(iris_df[iris_df['class']== 0].shape[0]))
print("Numero elementi classe 1 : {}".format(iris_df[iris_df['class']== 1].shape[0]))
print("Numero elementi classe 2 : {}".format(iris_df[iris_df['class']== 2].shape[0]))
#iris_df[iris_df['class']== 2].shape[0]

Numero elementi classe 0 : 50
Numero elementi classe 1 : 50
Numero elementi classe 2 : 50


## Creazione Nuovo Dataset per Binary Classification

In [10]:
class_0 = iris_df[iris_df['class']== 0] #Restituisce le righe con classe 0
class_1 = iris_df[iris_df['class']== 1] #Restituisce le righe con classe 1
class_2 = iris_df[iris_df['class']== 2] #Restituisce le righe con classe 2

class_0.head()#check

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   class  
0    0.0  
1    0.0  
2    0.0  
3    0.0  
4    0.0

### Primo Classificatore
- Classe 0 --> Classe Positiva
- (Classe1 + Classe2)-->Classe Negativa

In [19]:
classe_negativa_1 = np.r_[class_1,class_2] #concateniamo sulle righe
classe_negativa_1[:,-1] = 0 #sovrascrivo l'etichetta da 1 e 2 a 0
classe_positiva_1 = class_0.values
classe_positiva_1[:,-1] = 1 #sovrascrivo l'etichetta da 0 a 1

dataset1 = np.r_[classe_negativa_1 ,classe_positiva_1 ] #concateniamo sulle righe
X_1 = np.c_[np.ones((dataset1.shape[0],1)),dataset1[:,:4]]#prendiamo le prime 4 colonne del dataset1
y_1 = dataset1[:,-1].reshape(-1,1)#prendiamo l'ultima colonna del dataset1

print(X_1)
print(y_1)

[[1.  7.  3.2 4.7 1.4]
 [1.  6.4 3.2 4.5 1.5]
 [1.  6.9 3.1 4.9 1.5]
 [1.  5.5 2.3 4.  1.3]
 [1.  6.5 2.8 4.6 1.5]
 [1.  5.7 2.8 4.5 1.3]
 [1.  6.3 3.3 4.7 1.6]
 [1.  4.9 2.4 3.3 1. ]
 [1.  6.6 2.9 4.6 1.3]
 [1.  5.2 2.7 3.9 1.4]
 [1.  5.  2.  3.5 1. ]
 [1.  5.9 3.  4.2 1.5]
 [1.  6.  2.2 4.  1. ]
 [1.  6.1 2.9 4.7 1.4]
 [1.  5.6 2.9 3.6 1.3]
 [1.  6.7 3.1 4.4 1.4]
 [1.  5.6 3.  4.5 1.5]
 [1.  5.8 2.7 4.1 1. ]
 [1.  6.2 2.2 4.5 1.5]
 [1.  5.6 2.5 3.9 1.1]
 [1.  5.9 3.2 4.8 1.8]
 [1.  6.1 2.8 4.  1.3]
 [1.  6.3 2.5 4.9 1.5]
 [1.  6.1 2.8 4.7 1.2]
 [1.  6.4 2.9 4.3 1.3]
 [1.  6.6 3.  4.4 1.4]
 [1.  6.8 2.8 4.8 1.4]
 [1.  6.7 3.  5.  1.7]
 [1.  6.  2.9 4.5 1.5]
 [1.  5.7 2.6 3.5 1. ]
 [1.  5.5 2.4 3.8 1.1]
 [1.  5.5 2.4 3.7 1. ]
 [1.  5.8 2.7 3.9 1.2]
 [1.  6.  2.7 5.1 1.6]
 [1.  5.4 3.  4.5 1.5]
 [1.  6.  3.4 4.5 1.6]
 [1.  6.7 3.1 4.7 1.5]
 [1.  6.3 2.3 4.4 1.3]
 [1.  5.6 3.  4.1 1.3]
 [1.  5.5 2.5 4.  1.3]
 [1.  5.5 2.6 4.4 1.2]
 [1.  6.1 3.  4.6 1.4]
 [1.  5.8 2.6 4.  1.2]
 [1.  5.  2

### Secondo Classificatore
- Classe 1 --> Classe Positiva
- (Classe0 + Classe2)-->Classe Negativa

In [20]:
classe_negativa_2 = np.r_[class_0,class_2] #concateniamo sulle righe
classe_negativa_2[:,-1] = 0 #sovrascrivo l'etichetta da 0 e 2 a 0
classe_positiva_2 = class_1.values

dataset2 = np.r_[classe_negativa_2 ,classe_positiva_2 ] #concateniamo sulle righe
X_2 = np.c_[np.ones((dataset2.shape[0],1)),dataset2[:,:4]]#prendiamo le prime 4 colonne del dataset1
y_2 = dataset2[:,-1].reshape(-1,1)#prendiamo l'ultima colonna del dataset1

print(X_2)
print(y_2)


[[1.  5.1 3.5 1.4 0.2]
 [1.  4.9 3.  1.4 0.2]
 [1.  4.7 3.2 1.3 0.2]
 [1.  4.6 3.1 1.5 0.2]
 [1.  5.  3.6 1.4 0.2]
 [1.  5.4 3.9 1.7 0.4]
 [1.  4.6 3.4 1.4 0.3]
 [1.  5.  3.4 1.5 0.2]
 [1.  4.4 2.9 1.4 0.2]
 [1.  4.9 3.1 1.5 0.1]
 [1.  5.4 3.7 1.5 0.2]
 [1.  4.8 3.4 1.6 0.2]
 [1.  4.8 3.  1.4 0.1]
 [1.  4.3 3.  1.1 0.1]
 [1.  5.8 4.  1.2 0.2]
 [1.  5.7 4.4 1.5 0.4]
 [1.  5.4 3.9 1.3 0.4]
 [1.  5.1 3.5 1.4 0.3]
 [1.  5.7 3.8 1.7 0.3]
 [1.  5.1 3.8 1.5 0.3]
 [1.  5.4 3.4 1.7 0.2]
 [1.  5.1 3.7 1.5 0.4]
 [1.  4.6 3.6 1.  0.2]
 [1.  5.1 3.3 1.7 0.5]
 [1.  4.8 3.4 1.9 0.2]
 [1.  5.  3.  1.6 0.2]
 [1.  5.  3.4 1.6 0.4]
 [1.  5.2 3.5 1.5 0.2]
 [1.  5.2 3.4 1.4 0.2]
 [1.  4.7 3.2 1.6 0.2]
 [1.  4.8 3.1 1.6 0.2]
 [1.  5.4 3.4 1.5 0.4]
 [1.  5.2 4.1 1.5 0.1]
 [1.  5.5 4.2 1.4 0.2]
 [1.  4.9 3.1 1.5 0.2]
 [1.  5.  3.2 1.2 0.2]
 [1.  5.5 3.5 1.3 0.2]
 [1.  4.9 3.6 1.4 0.1]
 [1.  4.4 3.  1.3 0.2]
 [1.  5.1 3.4 1.5 0.2]
 [1.  5.  3.5 1.3 0.3]
 [1.  4.5 2.3 1.3 0.3]
 [1.  4.4 3.2 1.3 0.2]
 [1.  5.  3

### Terzo Classificatore
- Classe 2 --> Classe Positiva
- (Classe0 + Classe1)-->Classe Negativa

In [21]:
classe_negativa_3 = np.r_[class_0,class_1] #concateniamo sulle righe
classe_negativa_3[:,-1] = 0 #sovrascrivo l'etichetta da 0 e 1 a 0
classe_positiva_3 = class_2.values
classe_positiva_3[:,-1] = 1 #sovrascrivo l'etichetta da 2 a 1

dataset3 = np.r_[classe_negativa_3 ,classe_positiva_3 ] #concateniamo sulle righe
X_3 = np.c_[np.ones((dataset3.shape[0],1)),dataset3[:,:4]]#prendiamo le prime 4 colonne del dataset1
y_3 = dataset3[:,-1].reshape(-1,1)#prendiamo l'ultima colonna del dataset1

print(X_3)
print(y_3)


[[1.  5.1 3.5 1.4 0.2]
 [1.  4.9 3.  1.4 0.2]
 [1.  4.7 3.2 1.3 0.2]
 [1.  4.6 3.1 1.5 0.2]
 [1.  5.  3.6 1.4 0.2]
 [1.  5.4 3.9 1.7 0.4]
 [1.  4.6 3.4 1.4 0.3]
 [1.  5.  3.4 1.5 0.2]
 [1.  4.4 2.9 1.4 0.2]
 [1.  4.9 3.1 1.5 0.1]
 [1.  5.4 3.7 1.5 0.2]
 [1.  4.8 3.4 1.6 0.2]
 [1.  4.8 3.  1.4 0.1]
 [1.  4.3 3.  1.1 0.1]
 [1.  5.8 4.  1.2 0.2]
 [1.  5.7 4.4 1.5 0.4]
 [1.  5.4 3.9 1.3 0.4]
 [1.  5.1 3.5 1.4 0.3]
 [1.  5.7 3.8 1.7 0.3]
 [1.  5.1 3.8 1.5 0.3]
 [1.  5.4 3.4 1.7 0.2]
 [1.  5.1 3.7 1.5 0.4]
 [1.  4.6 3.6 1.  0.2]
 [1.  5.1 3.3 1.7 0.5]
 [1.  4.8 3.4 1.9 0.2]
 [1.  5.  3.  1.6 0.2]
 [1.  5.  3.4 1.6 0.4]
 [1.  5.2 3.5 1.5 0.2]
 [1.  5.2 3.4 1.4 0.2]
 [1.  4.7 3.2 1.6 0.2]
 [1.  4.8 3.1 1.6 0.2]
 [1.  5.4 3.4 1.5 0.4]
 [1.  5.2 4.1 1.5 0.1]
 [1.  5.5 4.2 1.4 0.2]
 [1.  4.9 3.1 1.5 0.2]
 [1.  5.  3.2 1.2 0.2]
 [1.  5.5 3.5 1.3 0.2]
 [1.  4.9 3.6 1.4 0.1]
 [1.  4.4 3.  1.3 0.2]
 [1.  5.1 3.4 1.5 0.2]
 [1.  5.  3.5 1.3 0.3]
 [1.  4.5 2.3 1.3 0.3]
 [1.  4.4 3.2 1.3 0.2]
 [1.  5.  3

## Addestramento Classificatori

In [14]:
def sigmoid(z):
    return(1 / (1 + np.exp(-z)))

In [15]:
def costFunction(theta, X, y):
    m = y.size
    h = sigmoid(X.dot(theta))
    
    J = -1*(1/m)*(np.log(h).T.dot(y) + np.log(1-h).T.dot(1-y))
               
    if np.isnan(J[0]):
        return(np.inf)
    return(J[0])

In [16]:
def gradient(theta, X, y):
    m = y.size
    h = sigmoid(X.dot(theta.reshape(-1,1)))
    
    grad =(1/m)*X.T.dot(h-y)

    return(grad.flatten())

In [22]:
initial_theta_1 = np.zeros((X_1.shape[1],1))#vettore parametri 5x1
initial_theta_2 = np.zeros((X_2.shape[1],1))#vettore parametri 5x1
initial_theta_3 = np.zeros((X_3.shape[1],1))#vettore parametri 5x1

res_1 = minimize(costFunction, initial_theta_1, args = (X_1, y_1), method = 'SLSQP', jac = gradient, options = {'maxiter' : 1000})
res_2 = minimize(costFunction, initial_theta_2, args = (X_2, y_2), method = 'SLSQP', jac = gradient, options = {'maxiter' : 1000})
res_3 = minimize(costFunction, initial_theta_3, args = (X_3, y_3), method = 'SLSQP', jac = gradient, options = {'maxiter' : 1000})

<ipython-input-15-57639f2c5c11>:5: RuntimeWarning: divide by zero encountered in log
  J = -1*(1/m)*(np.log(h).T.dot(y) + np.log(1-h).T.dot(1-y))


In [23]:
res_1


     fun: 3.9361426696499e-06
     jac: array([4.20703912e-06, 2.15809435e-05, 1.05565562e-05, 1.27716585e-05,
       4.62397805e-06])
 message: 'Optimization terminated successfully.'
    nfev: 25
     nit: 21
    njev: 21
  status: 0
 success: True
       x: array([  1.51369874,   2.71144116,   8.52666684, -12.64077846,
        -5.67495175])

In [24]:
res_2

     fun: 0.48356603243470975
     jac: array([4.55730391e-05, 1.62020514e-04, 2.79794730e-05, 1.66790150e-04,
       7.62369161e-05])
 message: 'Optimization terminated successfully.'
    nfev: 33
     nit: 31
    njev: 31
  status: 0
 success: True
       x: array([ 7.40469277, -0.24623542, -2.80313252,  1.31193535, -2.77419807])

In [25]:
res_3

     fun: 0.0396618985909295
     jac: array([1.71488138e-05, 7.34449767e-05, 6.28192109e-05, 7.52634973e-05,
       4.41562643e-05])
 message: 'Optimization terminated successfully.'
    nfev: 58
     nit: 55
    njev: 55
  status: 0
 success: True
       x: array([-42.74225356,  -2.46429642,  -6.68963589,   9.44071921,
        18.32617971])

In [26]:
theta_1 = res_1.x.reshape(-1,1) #Parametri dei 3 classificatori
theta_2 = res_2.x.reshape(-1,1)
theta_3 = res_3.x.reshape(-1,1)

In [27]:
example = iris_df.iloc[5,:]


print(example)

sepal length (cm)    5.4
sepal width (cm)     3.9
petal length (cm)    1.7
petal width (cm)     0.4
class                0.0
Name: 5, dtype: float64


In [38]:
#example = np.array([1,iris_df.iloc[5,:].values.reshape(1,-1)]) #Aggiunta scalare 1

#print(example)

arr = np.array(iris_df.iloc[5,:-1]).reshape(1,-1)

example = np.c_[np.ones((1,1)), arr]
print(example)
print(example.shape)

[[1.  5.4 3.9 1.7 0.4]]
(1, 5)


In [39]:
out_1 = sigmoid(example.dot(theta_1))
out_2 = sigmoid(example.dot(theta_2))
out_3 = sigmoid(example.dot(theta_3))

print(out_1)
print(out_2)
print(out_3)

[[1.]]
[[0.02328048]]
[[3.02791048e-26]]
